### ISSUE TITLE
Add {DJJ}: {JarJar}

### ISSUE THREAD

**Issue by mrspel1** [VenomProtocol/venomswap-community-token-list#2]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0xe3e267b18464F3CEE00D2e70E18981648998aE9A
Token Name (from contract): JarJar
Token Decimals (from contract): 16
Token Symbol (from contract): DJJ
Uniswap V2 Pair Address of Token: 0x9d914851019d1112003cff0e718639cc38472bef

Link to the official homepage of token: in the works
Link to CoinMarketCap or CoinGecko page of token: 

Token logo:

![jarjartokenlogo](https://user-images.githubusercontent.com/83910612/117573544-cd605880-b0d8-11eb-9798-7384d8579a33.png)

**Comment by 0xViper** [comment]
Added
